### PR TITLE
Attempt to fix upgrade.sh to support --cluster-init

### LINKED ISSUE #23: script don't work when using --cluster-init
```
+ upgrade
+ get_k3s_process_info
+ grep -E 'k3s .*(server|agent)'
+ ps -ef
+ grep -E -v '(init|grep|channelserver)'
+ awk '{print $1}'
+ K3S_PID=
+ '[' -z  ]
+ fatal 'K3s is not running on this server'
+ echo '[ERROR] ' 'K3s is not running on this server'
[ERROR]  K3s is not running on this server
+ exit 1
```

### PR DESCRIPTION
**Pull request by sixcorners**
Could fix #23

### CODE REVIEW

**Comment by e3b0c442** [comment]
I wonder if rather than using sed here, a quick update to the grep is all that's needed? 

`K3S_PID=$(ps -ef | grep -E "k3s .*(server|agent)" | grep -E -v "([^-]init|grep|channelserver)" | awk '{print $1}')`

Based on #5 they were trying to capture the case of a container init, so this should suffice.

@galal-hussein I don't suppose you have a chance to look at this? This bug has bitten me as well.

**Comment by engineer11111** [comment]
Hey guys, any chance to actually merge it? 
It would be great to have working updates on embedded ha setups.
Thank you:)

**Comment by brandond** [comment]
Relatively recent versions of k3s actually hide their command-line flags using setproctitle, so this shouldn't be necessary any longer. Are you running an older version of k3s with dqlite?

**Comment by engineer11111** [comment]
```ubuntu@node-1:~$ ./k3s --version
k3s version v1.19.7+k3s1 (5a00e38d)
ubuntu@node-1:~$ sudo ./k3s server --cluster-init &>/dev/null  &
[1] 1514
ubuntu@node-1:~$ 
ubuntu@node-1:~$ ps aux | grep k3s
root        1514  0.2  0.5  11164  4744 pts/0    S    08:39   0:00 sudo ./k3s server --cluster-init
root        1515 59.6 11.0 11301700 97744 pts/0  Sl   08:39   0:02 ./k3s server
ubuntu      1526  2.0  0.0   8160   736 pts/0    S+   08:39   0:00 grep --color=auto k3s
ubuntu@node-1:~$```

looks like it's not fixed unfortunately

**Comment by brandond** [comment]
@engineer11111 sure it is. Your sudo command has the full args but the actual k3s process below it does not.

**Comment by sixcorners** [comment]
I haven't checked it myself but it does look like it's fixed. Going to close this.

**Pull request closed without merging**
