### PR TITLE
Exclude PIDS belonging to supervise-daemon

### LINKED ISSUE #20: upgrade fails on k3os-based nodes
When attempting to upgrade with the `rancher/k3s-upgrade:v1.17.4-k3s1` tagged image, the upgrade script fails with,

```
+ upgrade
+ get_k3s_process_info
+ ps -ef
+ grep -E 'k3s .*(server|agent)'
+ grep -E -v '(init|grep|channelserver)'
+ awk '{print $1}'
+ K3S_PID='2429
2431'
+ '[' -z '2429
2431' ]
+ info 'K3S binary is running with pid 2429
2431'
+ echo '[INFO] ' 'K3S binary is running with pid 2429
2431'
[INFO]  K3S binary is running with pid 2429
2431
+ cat /host/proc/2429 2431/cmdline
+ awk '{print $1}'
+ head -n 1
cat: read error: Is a directory
cat: can't open '2431/cmdline': No such file or directory
+ K3S_BIN_PATH=
+ '[' '2429
2431' '==' 1 ]
+ '[' -z  ]
+ fatal 'Failed to fetch the k3s binary path from process 2429
2431'
+ echo '[ERROR] ' 'Failed to fetch the k3s binary path from process 2429
2431'
[ERROR]  Failed to fetch the k3s binary path from process 2429
2431
+ exit 1
```

... This seems to be related to the fact that two different PIDS match the [egreps](https://github.com/rancher/k3s-upgrade/blob/v1.17.4+k3s1/scripts/upgrade.sh#L15):

```
k3os-c [~]$ ps -ef | grep -E "k3s .*(server|agent)" | grep -E -v "(init|grep|channelserver)"
root      2429     1  0 Mar02 ?        00:00:00 supervise-daemon k3s-service --start --stdout /var/log/k3s-service.log --stderr /var/log/k3s-service.log --pidfile /var/run/k3s-service.pid --respawn-delay 5 /sbin/k3s -- agent --node-label k3os.io/mode=local --node-label k3os.io/version=v0.9.1
root      2431  2429  7 Mar02 ?        1-19:46:01 /sbin/k3s agent --node-label k3os.io/mode=local --node-label k3os.io/version=v0.9.1
```

### PR DESCRIPTION
**Pull request by billimek**
Fixes #20

### CODE REVIEW

**Comment by billimek** [comment]
Based on a slack conversation, I wonder if this is even needed?  It was confirmed that this style of upgrade is not intended for k3os-based nodes.

If confirmed, I can close this PR and associated issue.

**Comment by dweomer** [comment]
@billimek k3os upgrades are currently outside the scope of this project.

**Comment by srueg** [comment]
This is also is an issue on regular Alpine hosts running OpenRC. So 👍 for this PR.

**Comment by dweomer** [comment]
Superceded by #26

**Pull request closed without merging**
